package store

import (
	"context"
	"database/sql"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/unkabas/dbil/internal/crypto"
)

// Role values stored in the users.role column.
const (
	RoleAdmin  = "admin"
	RoleMember = "member"
	RoleViewer = "viewer"
)

// passwordHashLen is the Argon2id output length used for stored hashes.
const passwordHashLen = 32

// ErrUserExists is returned by Create when the supplied email is already
// taken (UNIQUE constraint).
var ErrUserExists = errors.New("user already exists")

// ErrUserNotFound is returned when an email lookup misses.
var ErrUserNotFound = errors.New("user not found")

// UserAuth bundles a user row with its password material. Used only inside
// auth/store; never serialise this type in API responses.
type UserAuth struct {
	User
	PasswordHash string
	PasswordSalt []byte
}

// User is the row from the users table without the password material.
type User struct {
	ID         int64
	Email      string
	Role       string
	MustRotate bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// UsersRepo wraps user-related queries.
type UsersRepo struct {
	DB *sql.DB
}

// NewUsersRepo binds a UsersRepo to db.
func NewUsersRepo(db *sql.DB) *UsersRepo {
	return &UsersRepo{DB: db}
}

// Create inserts a new user. Password is hashed with Argon2id and a fresh
// salt. If autoGenerated is true, must_rotate=1 so the UI forces a change
// at first login.
func (r *UsersRepo) Create(ctx context.Context, email, password, role string, autoGenerated bool) (User, error) {
	if email == "" || password == "" {
		return User{}, errors.New("users: email and password are required")
	}
	switch role {
	case RoleAdmin, RoleMember, RoleViewer:
	default:
		return User{}, fmt.Errorf("users: invalid role %q", role)
	}
	salt, err := crypto.NewSalt()
	if err != nil {
		return User{}, fmt.Errorf("users: salt: %w", err)
	}
	hash, err := crypto.Argon2id([]byte(password), salt, passwordHashLen)
	if err != nil {
		return User{}, fmt.Errorf("users: hash: %w", err)
	}
	encoded := base64.RawURLEncoding.EncodeToString(hash)

	now := time.Now().UnixNano()
	mustRotate := 0
	if autoGenerated {
		mustRotate = 1
	}
	res, err := r.DB.ExecContext(ctx, `
		INSERT INTO users (email, password_hash, password_salt, role, must_rotate, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?, ?, ?)`,
		email, encoded, salt, role, mustRotate, now, now,
	)
	if err != nil {
		if strings.Contains(err.Error(), "UNIQUE constraint") {
			return User{}, ErrUserExists
		}
		return User{}, fmt.Errorf("users: insert: %w", err)
	}
	id, _ := res.LastInsertId()
	return User{
		ID:         id,
		Email:      email,
		Role:       role,
		MustRotate: autoGenerated,
		CreatedAt:  time.Unix(0, now),
		UpdatedAt:  time.Unix(0, now),
	}, nil
}

// AdminExists reports whether at least one row with role='admin' is present.
// Used by bootstrap to skip admin creation on subsequent runs.
func (r *UsersRepo) AdminExists(ctx context.Context) (bool, error) {
	var n int
	err := r.DB.QueryRowContext(ctx, `SELECT COUNT(*) FROM users WHERE role = ?`, RoleAdmin).Scan(&n)
	if err != nil {
		return false, fmt.Errorf("users: count admins: %w", err)
	}
	return n > 0, nil
}

// GetUserAuthByEmail returns the user along with the credentials needed by
// the auth package to verify a password. Returns ErrUserNotFound on miss.
func (r *UsersRepo) GetUserAuthByEmail(ctx context.Context, email string) (UserAuth, error) {
	var (
		ua         UserAuth
		mustRotate int
		createdNS  int64
		updatedNS  int64
	)
	err := r.DB.QueryRowContext(ctx, `
		SELECT id, email, password_hash, password_salt, role, must_rotate, created_at, updated_at
		FROM users WHERE email = ?`, email,
	).Scan(
		&ua.User.ID, &ua.User.Email, &ua.PasswordHash, &ua.PasswordSalt,
		&ua.User.Role, &mustRotate, &createdNS, &updatedNS,
	)
	if errors.Is(err, sql.ErrNoRows) {
		return UserAuth{}, ErrUserNotFound
	}
	if err != nil {
		return UserAuth{}, fmt.Errorf("users: get auth by email: %w", err)
	}
	ua.User.MustRotate = mustRotate != 0
	ua.User.CreatedAt = time.Unix(0, createdNS)
	ua.User.UpdatedAt = time.Unix(0, updatedNS)
	return ua, nil
}
